package com.botmaker.dashboard.github;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class SubmissionTest {

    private static final ObjectMapper MAPPER = new ObjectMapper();

    private static Submission with(String repo, String... files) {
        return new Submission(repo, 12, "add a plugin", "someone", "abc123",
                "https://github.com/x", List.of(files), Checks.unknown());
    }

    private static JsonNode json(String text) {
        try {
            return MAPPER.readTree(text);
        } catch (Exception e) {
            throw new AssertionError(e);
        }
    }

    @Test
    void oneEntryFileAndNothingElseIsTheShapeTheLayoutExistsFor() {
        Submission plugin = with(Queue.REGISTRY, "plugins/com.example.demo.json");
        assertTrue(plugin.wellShaped());
        assertEquals("com.example.demo", plugin.claimedId().orElseThrow());
        assertEquals("adds plugins/com.example.demo.json", plugin.shape());

        Submission bot = with(Queue.GALLERY, "bots/someone-a-bot.json");
        assertTrue(bot.wellShaped());
        assertEquals("someone-a-bot", bot.claimedId().orElseThrow());
    }

    @Test
    void aPullRequestTouchingAnythingBesidesItsEntryIsFlagged() {
        // index.json is generated by CI from the entry files, so a submission editing it will be stale the
        // moment another one merges. It is the most common stray and must be loud, not merely present.
        Submission sneaky = with(Queue.REGISTRY, "plugins/com.example.demo.json", "index.json");
        assertFalse(sneaky.wellShaped());
        assertEquals(List.of("index.json"), sneaky.strays());
        assertTrue(sneaky.shape().contains("it should not"));
    }

    @Test
    void twoEntryFilesAreNoEntryFileAtAll() {
        // Two claims in one pull request is not "one of them is the entry": which id is being claimed has no
        // answer, so there is nothing to render as fields and nothing safe to merge.
        Submission two = with(Queue.REGISTRY,
                "plugins/com.example.one.json", "plugins/com.example.two.json");
        assertTrue(two.entryFile().isEmpty());
        assertFalse(two.wellShaped());
        assertTrue(two.shape().startsWith("no entry file"));
    }

    @Test
    void aFileDeeperThanTheEntryDirectoryIsNotAnEntry() {
        Submission nested = with(Queue.REGISTRY, "plugins/nested/thing.json");
        assertTrue(nested.entryFile().isEmpty());
    }

    @Test
    void aPullRequestIsReadWithoutInterpretingAnythingAboutIt() {
        JsonNode pr = json("""
                {"number": 7, "title": "add com.example.demo", "user": {"login": "octocat"},
                 "head": {"sha": "deadbeef"}, "html_url": "https://github.com/x/y/pull/7"}
                """);
        JsonNode files = json("""
                [{"filename": "plugins/com.example.demo.json", "status": "added"}]
                """);
        Submission read = Submission.read(Queue.REGISTRY, pr, Submission.filenames(files), Checks.unknown());
        assertEquals(7, read.number());
        assertEquals("octocat", read.author());
        assertEquals("deadbeef", read.headSha());
        assertEquals("botmaker-plugin-registry#7", read.label());
    }
}
