package com.botmaker.dashboard.umbrella;

import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DepsEnvTest {

    private static final String STUDIO = """
            # Generated by the umbrella release.sh — do not hand-edit except to test an unreleased upstream
            # locally (any git ref works: a tag, a branch, a SHA).

            SHARED_TAG=v0.0.20
            SESSION_TAG=v0.0.12
            STUDIO_API_TAG=v0.0.4
            PLUGIN_HOST_TAG=v0.0.5
            """;

    @Test
    void marksAPinThatIsNotTheUpstreamsNewestTag() {
        List<DepsEnv.Pin> pins = DepsEnv.parse(STUDIO, Map.of(
                "botmaker-shared", "v0.0.21",
                "botmaker-session", "v0.0.12",
                "botmaker-studio-api", "v0.0.4",
                "botmaker-plugin-host", "v0.0.5"));

        assertEquals(4, pins.size());
        assertTrue(pins.get(0).stale());
        assertEquals("SHARED_TAG=v0.0.20 (upstream v0.0.21)", pins.get(0).toString());
        assertFalse(pins.get(1).stale());
    }

    @Test
    void aPinWithNoKnownUpstreamIsUnjudgedRatherThanCurrent() {
        // The upstream's tag is unknown when its checkout is missing or its git could not be read. Saying
        // "current" there would be a claim; saying nothing is the truth.
        List<DepsEnv.Pin> pins = DepsEnv.parse(STUDIO, Map.of());

        assertTrue(pins.stream().noneMatch(DepsEnv.Pin::stale));
        assertEquals("SHARED_TAG=v0.0.20", pins.get(0).toString());
    }

    @Test
    void anUnrecognisedKeyStillShows() {
        // A key this version does not know is a NEW upstream, which is exactly when hiding it would be worst.
        List<DepsEnv.Pin> pins = DepsEnv.parse("SOMETHING_NEW_TAG=v9.9.9\n", Map.of());

        assertEquals(1, pins.size());
        assertTrue(pins.get(0).module().isEmpty());
        assertEquals("SOMETHING_NEW_TAG=v9.9.9", pins.get(0).toString());
    }

    @Test
    void ignoresCommentsBlanksAndAValuelessKey() {
        assertTrue(DepsEnv.parse("# a comment\n\nSHARED_TAG=\nnot-an-assignment\n", Map.of()).isEmpty());
    }
}
