package com.botmaker.dashboard.github;

import com.fasterxml.jackson.databind.JsonNode;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.regex.Pattern;

/**
 * One open pull request on the plugin registry or the gallery: who opened it, what one file it adds, and
 * what the gate said about it.
 *
 * <p><b>The shape is the check this class makes, and it is the only one.</b> Both data repositories are
 * one file per entry — {@code plugins/<plugin-id>.json} and {@code bots/<owner>-<repo>.json} — and that
 * layout exists so a submission is exactly one added file: two submissions on the same day cannot conflict,
 * git itself refuses a second claim on an id, and {@code index.json} is generated by CI rather than edited.
 * So a pull request touching anything besides its own entry file is the shape the layout was chosen to make
 * impossible, and it is flagged loudly rather than being left for the reviewer to notice in the Files tab.
 *
 * <p>Everything else about whether the submission is *good* belongs to the registry's own CI, which runs
 * {@code RegistryGate} out of {@code botmaker-cli}'s main artifact — see {@link Checks}. This record parses
 * a pull request; it validates no plugin.
 *
 * @param repo    {@code owner/name} of the repository the pull request is on
 * @param number  the pull request number
 * @param title   its title, as submitted
 * @param author  the login that opened it
 * @param headSha the head commit — what the check runs are attached to
 * @param url     its page on github.com
 * @param files   every path the pull request touches
 * @param checks  the gate's verdict for {@link #headSha}
 * @param labels  the pull request's label names — the gallery's merge job speaks through two of them
 */
public record Submission(String repo, int number, String title, String author, String headSha,
                         String url, List<String> files, Checks checks, List<String> labels) {

    /**
     * The one shape a submission may have.
     *
     * <p>All three directories in one pattern rather than one per repository: the rule is the same rule, and
     * a per-repo copy would be a second place to edit when a fourth appears. {@code vetted/} is the gallery's
     * maintainer-only one — a vetting is also exactly one file, opened from this window's Catalog tab.
     */
    private static final Pattern ENTRY = Pattern.compile("(plugins|bots|vetted)/[^/]+\\.json");

    /** The label {@code automerge.yml} puts on a listing over its author's new-listings limit. */
    public static final String LABEL_WAITING = "waiting";

    /** The label {@code automerge.yml} puts on a listing it will not merge by itself. */
    public static final String LABEL_NEEDS_MAINTAINER = "needs-maintainer";

    public Submission {
        files = List.copyOf(files);
        labels = labels == null ? List.of() : List.copyOf(labels);
    }

    /** Reads a pull request object and the file list that goes with it. */
    public static Submission read(String repo, JsonNode pr, List<String> files, Checks checks) {
        List<String> labels = new ArrayList<>();
        for (JsonNode label : pr.path("labels")) {
            labels.add(label.path("name").asText(""));
        }
        return new Submission(
                repo,
                pr.path("number").asInt(),
                pr.path("title").asText(""),
                pr.path("user").path("login").asText("(unknown)"),
                pr.path("head").path("sha").asText(""),
                pr.path("html_url").asText(""),
                files,
                checks,
                labels);
    }

    /**
     * What the gallery's merge job has decided, in one word — blank for the plugin registry, which merges by
     * hand, and for a listing it has not labelled.
     *
     * <p>Read off the labels {@code automerge.yml} sets rather than recomputed: the policy is
     * {@code botmaker-cli}'s {@code ListingPolicy}, and a second reading of it here would be the second
     * implementation this window exists not to have. An unlabelled open listing is one whose checks are
     * still running, or failed, or that the job has not reached yet — the Gate column says which.
     */
    public String autoMerge() {
        if (labels.contains(LABEL_NEEDS_MAINTAINER)) return "needs maintainer";
        if (labels.contains(LABEL_WAITING)) return "waiting (rate limit)";
        if (!repo.equals(Queue.GALLERY)) return "";
        return files.stream().allMatch(f -> f.startsWith("bots/")) && !files.isEmpty()
                ? "merges when checks pass" : "";
    }

    /** The paths of a pull request's changed files, from {@code GET /pulls/{n}/files}. */
    public static List<String> filenames(JsonNode fileArray) {
        if (fileArray == null || !fileArray.isArray()) {
            return List.of();
        }
        List<String> out = new ArrayList<>();
        for (JsonNode f : fileArray) {
            out.add(f.path("filename").asText(""));
        }
        return List.copyOf(out);
    }

    /** The entry file this submission adds, when it adds exactly one. */
    public Optional<String> entryFile() {
        List<String> entries = files.stream().filter(f -> ENTRY.matcher(f).matches()).toList();
        return entries.size() == 1 ? Optional.of(entries.get(0)) : Optional.empty();
    }

    /**
     * Everything touched that is not the entry file.
     *
     * <p>{@code index.json} shows up here when somebody edits it by hand, and that is the most common
     * stray: it is generated by CI from the entry files, so a pull request carrying it will be out of date
     * the moment another one merges.
     */
    public List<String> strays() {
        Optional<String> entry = entryFile();
        return files.stream().filter(f -> entry.isEmpty() || !f.equals(entry.get())).toList();
    }

    /** True when this is exactly one entry file and nothing else — the shape the layout is designed for. */
    public boolean wellShaped() {
        return entryFile().isPresent() && strays().isEmpty();
    }

    /** The id a plugin claims, or the {@code owner-repo} a bot claims: the entry's filename, which is its identity. */
    public Optional<String> claimedId() {
        return entryFile().map(f -> f.substring(f.indexOf('/') + 1, f.length() - ".json".length()));
    }

    /** One line for the row: what this submission adds, or why its shape is wrong. */
    public String shape() {
        if (files.isEmpty()) {
            return "no files read";
        }
        if (entryFile().isEmpty()) {
            return "no entry file — touches " + String.join(", ", files);
        }
        List<String> strays = strays();
        if (strays.isEmpty()) {
            return "adds " + entryFile().orElseThrow();
        }
        return "adds " + entryFile().orElseThrow() + " AND " + strays.size()
                + " file(s) it should not: " + String.join(", ", strays);
    }

    /** {@code botmaker-plugin-registry#12}, which is how the operator will refer to it out loud. */
    public String label() {
        return repo.substring(repo.indexOf('/') + 1) + "#" + number;
    }
}
